version: "3"

services:
  web:
    build: ./
    environment:
      - POSTGRES_HOST=db
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3030:3000"
      - "4000:4000"
    depends_on:
      - db
    links:
      - db

  db:
    image: kartoza/postgis:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
